/* Generated by ggpng2tile from bullseye.png */

/* https://github.com/codercowboy/ggpng2tile */

/* 8x8 px — 1 tile, 1 color + transparent */

#ifndef BULLSEYE_H
#define BULLSEYE_H

#define bullseye_tiles_count 1
#define bullseye_tiles_size_bytes 32

extern const unsigned char bullseye_tiles[32];

#define bullseye_palette_color_count 16
#define bullseye_palette_size_bytes 32

extern const unsigned char bullseye_palette[32];

#endif
