/*
  Generated by ggpng2tile (https://github.com/codercowboy/ggpng2tile) on 2026-06-21T01:00:11.789Z 
  source file: bullseye.png, dims: 8x8 px, tiles: 1, palette: 2 colors + transparent
*/

#ifndef BULLSEYE_H
#define BULLSEYE_H

#define bullseye_tiles_count 1
#define bullseye_tiles_size_bytes 32

extern const unsigned char bullseye_tiles[32];

#define bullseye_palette_color_count 16
#define bullseye_palette_size_bytes 32

extern const unsigned char bullseye_palette[32];

#endif
