/* Generated by ggpng2tile from ega_sample.png */

/* https://github.com/codercowboy/ggpng2tile */

/* 8x8 px — 1 tile, 15 colors + transparent */

#ifndef EGA_SAMPLE_H
#define EGA_SAMPLE_H

#define ega_sample_tiles_count 1
#define ega_sample_tiles_size_bytes 32

extern const unsigned char ega_sample_tiles[32];

#define ega_sample_palette_color_count 16
#define ega_sample_palette_size_bytes 32

extern const unsigned char ega_sample_palette[32];

#endif
