/*
  Generated by ggpng2tile (https://github.com/codercowboy/ggpng2tile) on 2026-06-21T01:00:11.842Z 
  source file: ega_sample.png, dims: 8x8 px, tiles: 1, palette: 15 colors + transparent
*/

#ifndef EGA_SAMPLE_H
#define EGA_SAMPLE_H

#define ega_sample_tiles_count 1
#define ega_sample_tiles_size_bytes 32

extern const unsigned char ega_sample_tiles[32];

#define ega_sample_palette_color_count 16
#define ega_sample_palette_size_bytes 32

extern const unsigned char ega_sample_palette[32];

#endif
