/* Generated by ggpng2tile from ega_sample.png */
/* 8x8 px — 1 tile, 15 colors + transparent */

#ifndef EGA_SAMPLE_H
#define EGA_SAMPLE_H

extern const unsigned char ega_sample_tiles[32];
extern const unsigned char ega_sample_palette[32];

#define EGA_SAMPLE_NUM_TILES 1
#define EGA_SAMPLE_TILES_SIZE 32
#define EGA_SAMPLE_PALETTE_SIZE 32

#endif
