/* Generated by ggpng2tile from ship.png */

/* https://github.com/codercowboy/ggpng2tile */

/* 16x16 px — 4 tiles, 5 colors + transparent */

#ifndef SHIP_H
#define SHIP_H

#define ship_tiles_count 4
#define ship_tiles_size_bytes 128

extern const unsigned char ship_tiles[128];

#define ship_palette_color_count 16
#define ship_palette_size_bytes 32

extern const unsigned char ship_palette[32];

#endif
