/* Generated by ggpng2tile from ship.png */
/* 16x16 px — 4 tiles, 6 colors + transparent */
/* https://github.com/codercowboy/ggpng2tile */

#ifndef SHIP_H
#define SHIP_H

extern const unsigned char ship_tiles[128];
extern const unsigned char ship_palette[32];

#define SHIP_NUM_TILES 4
#define SHIP_TILES_SIZE 128
#define SHIP_PALETTE_SIZE 32

#endif
