import fs from 'fs';
import path from 'path';
import { PNG } from 'pngjs';
import { denull } from './GGPNG2TileUtils.js';
import { HexUtils } from './HexUtils.js';
import { PaletteManager, PaletteEntry } from "./PaletteManager.js";

export class PNG2TileConverter {
    /**
    * Convert the pngFilePath PNG to GG tile data and return the generated C source
    * and header as strings, along with metadata about the conversion.
    *
    * This method is the public programmatic API — call it directly if you want
    * the output strings without writing files to disk.
    *
    * @returns {{ cFileContents: string, hFileContents: string, varName: string, numTiles: number,
    *             numColors: number, width: number, height: number }}
    */
    static convertPNGToTile(pngFilePath, paletteManager, varName = null, cFilePath = null, hFilePath = null) {
        varName = denull(varName, path.basename(pngFilePath, '.png').replace(/[^a-zA-Z0-9]/g, '_'));
        cFilePath = denull(cFilePath, path.dirname(pngFilePath) + "/" + varName + ".c");
        hFilePath = denull(path.dirname(pngFilePath) + "/" + varName + ".h");
        console.log(`Converting ${pngFilePath} to ${cFilePath} and ${hFilePath}`);

        const pngFileContents = fs.readFileSync(pngFilePath);

        // PNG.sync.read decodes the file into a flat RGBA buffer regardless of
        // whether the source was 8-bit indexed, 24-bit RGB, 32-bit RGBA, etc.
        // After this call, png.data is always a Uint8Array of (width * height * 4)
        // bytes laid out as [R, G, B, A, R, G, B, A, ...] from top-left to bottom-right.
        const pngMetadata = PNG.sync.read(pngFileContents);
        const { data, width, height } = pngMetadata;

        let pngWidthPixels = width, pngHeightPixels = height, pngData = data;

        // The GG tile format is built around 8x8 blocks. A sprite sheet that is
        // e.g. 17 pixels wide has no valid tile boundary at the right edge.
        if (pngWidthPixels % 8 !== 0 || pngHeightPixels % 8 !== 0) {
            console.error(`Error: image size ${pngWidthPixels}x${pngHeightPixels} is not a multiple of 8`);
            process.exit(1);
        }

        let paletteEntriesArray = paletteManager.getPaletteEntries();

        const paletteColorWords = new Array(16).fill(0);
        for (let paletteEntry of paletteEntriesArray) {
            let paletteColorWord = PNG2TileConverter.#packGGColor(paletteEntry.red, paletteEntry.green, paletteEntry.blue);
            paletteColorWords[paletteEntry.index] = paletteColorWord;
        }

        // Encode tiles left-to-right, top-to-bottom — the order the GG expects
        // them in VRAM when using sequential tile indices.
        const tilesCountX = pngWidthPixels / 8;
        const tilesCountY = pngHeightPixels / 8;
        const tileBytes = [];
        for (let tileY = 0; tileY < tilesCountY; tileY++) {
            for (let tileX = 0; tileX < tilesCountX; tileX++) {
                tileBytes.push(...PNG2TileConverter.#encodeTileGGFormat(pngData, pngWidthPixels, paletteManager, tileX, tileY));
            }
        }

        const numTiles = tilesCountX * tilesCountY;

        let dateString = new Date().toISOString();
        const fileHeader = [
            `/*`,
            `  Generated by ggpng2tile (https://github.com/codercowboy/ggpng2tile) on ${new Date().toISOString()} `,
            `  source png file: ${path.basename(pngFilePath)}, dims: ${pngWidthPixels}x${pngHeightPixels}px, tiles: ${numTiles}, palette color count: ${paletteEntriesArray.length}`,
            `*/`,
            ``,
        ].join('\n');

        const cFileContents = [
            fileHeader,
            PNG2TileConverter.#toCTilesArraySoureCode(`${varName}_tiles`, tileBytes, 4),
            ``,
            PNG2TileConverter.#toCPaletteArraySourceCode(`${varName}_palette`, paletteColorWords),
            ``,
        ].join('\n');

        let paletteDescription = "`/*\n   Palette Colors\n";
        for (let paletteEntry of paletteEntriesArray) {
            let paletteColorWord = PNG2TileConverter.#packGGColor(paletteEntry.red, paletteEntry.green, paletteEntry.blue);
            let ggFormatFirstByteString = HexUtils.toHex2(paletteColorWord & 0xFF, "0x") + " "; // first byte of word 
            let ggFormatSecondByteString = HexUtils.toHex2((paletteColorWord >> 8) & 0xFF, "0x") + ", "; // second byte of word
            let ggFormatBytesString = `${ggFormatFirstByteString} ${ggFormatSecondByteString}`;
            paletteDescription += `   Color index #${paletteEntry.index}, gg format: ${ggFormatBytesString} rgba: ${paletteEntry.toCSSRGBA()}, html: ${paletteEntry.toHTMLHex()}\n`;
        }
        paletteDescription += `*/`;

        const paletteColorCount = paletteEntriesArray.length;
        const paletteSizeBytes = paletteColorCount * 2;

        const hFileContents = [
            fileHeader,
            `#ifndef ${varName.toUpperCase()}_H`,
            `#define ${varName.toUpperCase()}_H`,
            ``,
            `#define ${varName}_source_image_width_pixels ${pngWidthPixels}`,
            `#define ${varName}_source_image_height_pixels ${pngHeightPixels}`,
            ``,
            `#define ${varName}_tiles_count ${numTiles}`,
            `#define ${varName}_tiles_width ${tilesCountX}`,
            `#define ${varName}_tiles_height ${tilesCountY}`,
            ``,
            `#define ${varName}_tiles_size_bytes ${tileBytes.length}`,
            `extern const unsigned char ${varName}_tiles[${tileBytes.length}];`,
            ``,
            `${paletteDescription}`,
            ``,
            `#define ${varName}_palette_color_count ${paletteColorCount}`,
            ``,
            `#define ${varName}_palette_size_bytes ${paletteSizeBytes}`,
            `extern const unsigned char ${varName}_palette[${paletteSizeBytes}];`,
            ``,
            `#endif`,
            ``,
        ].join('\n');

        fs.writeFileSync(cFilePath, cFileContents);
        fs.writeFileSync(hFilePath, hFileContents);
        console.log(`Wrote ${varName}.c and ${varName}.h`);
    }

    // ---------------------------------------------------------------------------
    // Private helpers
    // ---------------------------------------------------------------------------

    /**
     * Encode one 8x8 tile at tile-grid position (tileX, tileY) into 32 bytes
     * of GG planar tile data.
     *
     * GG planar format — each row of 8 pixels becomes 4 bytes (one per bitplane):
     *
     *   byte 0 = bitplane 0: bit 0 (LSB) of each pixel's palette index
     *   byte 1 = bitplane 1: bit 1 of each pixel's palette index
     *   byte 2 = bitplane 2: bit 2 of each pixel's palette index
     *   byte 3 = bitplane 3: bit 3 (MSB) of each pixel's palette index
     *
     * Within each byte, pixel 0 of the row sits in the MSB (bit 7), and pixel 7
     * sits in the LSB (bit 0).
     *
     * Worked example — 8 pixels all at palette index 1 (binary 0001):
     *
     *   For each pixel, idx = 1 = 0b0001
     *
     *   Bitplane 0 checks (idx & (1 << 0)) = (1 & 1) = 1  → all 8 pixels set a bit
     *     → bp[0] = 0b11111111 = 0xFF
     *   Bitplane 1 checks (idx & (1 << 1)) = (1 & 2) = 0  → no bits set
     *     → bp[1] = 0x00
     *   Bitplane 2 checks (idx & (1 << 2)) = (1 & 4) = 0
     *     → bp[2] = 0x00
     *   Bitplane 3 checks (idx & (1 << 3)) = (1 & 8) = 0
     *     → bp[3] = 0x00
     *
     *   Row output: 0xFF 0x00 0x00 0x00
     *
     * Another example — 8 pixels all at palette index 6 (binary 0110):
     *
     *   Bitplane 0: (6 & 1) = 0 → bp[0] = 0x00
     *   Bitplane 1: (6 & 2) = 2 → non-zero, all pixels set → bp[1] = 0xFF
     *   Bitplane 2: (6 & 4) = 4 → non-zero, all pixels set → bp[2] = 0xFF
     *   Bitplane 3: (6 & 8) = 0 → bp[3] = 0x00
     *
     *   Row output: 0x00 0xFF 0xFF 0x00
     *
     * @param {byte[]} pngData - Decoded pngjs PNG object data.
     * @param {number} pngWidthPixels - Decoded pngjs PNG object width.
     * @param {PaletteManager} paletteManager - PaletteManager
     * @param {number} tileX - Tile column index (0-based).
     * @param {number} tileY - Tile row index (0-based).
     * @returns {number[]} 32 bytes of encoded tile data.
     */
    static #encodeTileGGFormat(pngData, pngWidthPixels, paletteManager, tileX, tileY) {
        const bytes = [];

        for (let row = 0; row < 8; row++) {
            // bp[0..3] accumulate one byte per bitplane for this row of 8 pixels.
            const bp = [0, 0, 0, 0];

            for (let col = 0; col < 8; col++) {
                // Convert tile-local (col, row) to absolute pixel (px, py), then to
                // the flat RGBA buffer index. Same formula as in #buildPalette:
                //   i = (absoluteY * width + absoluteX) * 4
                //
                // Example: col=2, row=1 in tile (1, 0) on a 16px-wide image:
                //   px = 1*8 + 2 = 10,  py = 0*8 + 1 = 1
                //   i  = (1 * 16 + 10) * 4 = 26 * 4 = 104
                const i = ((tileY * 8 + row) * pngWidthPixels + (tileX * 8 + col)) * 4;

                const red = pngData[i], green = pngData[i + 1], blue = pngData[i + 2];
                const alpha = parseFloat(pngData[i + 3]) / 255.0;
                const paletteEntry = paletteManager.getNearestPaletteEntry(red, green, blue, alpha);
                const paletteColorIndex = paletteEntry.index;

                // Within a bitplane byte, pixel 0 occupies the MSB (bit 7) and pixel 7
                // occupies the LSB (bit 0). So for column `col`, the target bit position
                // inside the byte is (7 - col).
                //
                // Example: col=0 → bit 7 (MSB),  col=7 → bit 0 (LSB)
                const bit = 7 - col;

                // Distribute the palette index across the 4 bitplane bytes.
                // For each bitplane p (0-3), check whether bit p of the index is set.
                // If it is, set the corresponding pixel's bit in bp[p].
                //
                // (1 << p)   — a mask isolating bit p of the index
                // (1 << bit) — a mask for this pixel's position in the bitplane byte
                //
                // Example: idx=3 (0b0011), col=0 (bit position 7)
                //   p=0: (3 & 1) = 1 → bp[0] |= (1 << 7) → sets bit 7 of bp[0]
                //   p=1: (3 & 2) = 2 → bp[1] |= (1 << 7) → sets bit 7 of bp[1]
                //   p=2: (3 & 4) = 0 → bp[2] unchanged
                //   p=3: (3 & 8) = 0 → bp[3] unchanged
                for (let p = 0; p < 4; p++) {
                    if (paletteColorIndex & (1 << p)) {
                        bp[p] |= (1 << bit);
                    }
                }
            }

            // Emit bitplane bytes in order 0→3 (LSB plane first — see README for
            // why this feels backwards compared to how you'd write the index in binary).
            bytes.push(...bp);
        }

        return bytes;
    }

    /**
     * Render a flat byte array as a C unsigned char array definition.
     *
     * Output example for a 4-byte array named "ship_tiles":
     *
     *   const unsigned char ship_tiles[4] = {
     *       0xff, 0x00, 0x00, 0x00,
     *   };
     *
     * @param {string} varName - The C variable name.
     * @param {number[]} bytes - Array of byte values (0-255).
     * @param {number} cols - How many hex values to print per line (default 16).
     */
    static #toCTilesArraySoureCode(varName, bytes, cols = 16) {
        const lines = [`const unsigned char ${varName}[${bytes.length}] = {`];
        let line = "    ";
        let colCount = 0;
        for (let i = 0; i < bytes.length; i++) {
            line += HexUtils.toHex2(bytes[i], "0x") + ", ";
            colCount += 1;
            if (colCount == cols) {
                colCount = 0;
                lines.push(line.slice(0, line.length - 1));
                line = "    ";
            }
        }
        if (colCount > 0) {
            lines.push(line.slice(0, line.length - 1));
        }
        lines.push(`};`);
        return lines.join('\n');
    }

    /**
     * Render a 16-entry GG palette as a C unsigned char array of raw little-endian
     * bytes. Each 12-bit GG color word is stored as 2 bytes (LE), so 16 palette
     * entries become 32 bytes total.
     *
     * Outputting as unsigned char (rather than unsigned short) makes the 2-bytes-
     * per-entry layout explicit and avoids any ambiguity around short/int sizes
     * across different Z80 toolchains.
     *
     * Byte layout for one entry (LE 16-bit word 0x0RGB):
     *   byte 0 (low):  GGGG RRRR
     *   byte 1 (high): 0000 BBBB
     *
     * Output example (cols=8 entries per line = 16 bytes per line):
     *
     *   const unsigned char ship_palette[32] = {
     *       0x00, 0x00, 0x00, 0x0f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
     *       0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
     *   };
     *
     * @param {string} varName - The C variable name.
     * @param {number[]} words - Array of 16 palette word values.
     * @param {number} cols - Palette entries per line (default 8 → 16 bytes per line).
     */
    static #toCPaletteArraySourceCode(varName, words, cols = 8) {
        const lines = [`const unsigned char ${varName}[${words.length * 2}] = {`];
        let line = "    ";
        let colCount = 0;
        for (let i = 0; i < words.length; i++) {
            line += HexUtils.toHex2(words[i] & 0xFF, "0x") + ", "; // first byte of word 
            line += HexUtils.toHex2((words[i] >> 8) & 0xFF, "0x") + ", "; // second byte of word
            colCount += 1;
            if (colCount == cols) {
                colCount = 0;
                lines.push(line.slice(0, line.length - 1));
                line = "    ";
            }
        }
        if (colCount > 0) {
            lines.push(line.slice(0, line.length - 1));
        }
        lines.push(`};`);
        return lines.join('\n');
    }

    /**
     * Scale an 8-bit color channel (0-255) down to a 4-bit value (0-15).
     *
     * The Game Gear stores each color channel as 4 bits, giving 16 possible
     * intensities per channel (0-15) instead of the 256 (0-255) you get in
     * a standard 8-bit channel.
     *
     * We shift right by 4 to divide by 16, which maps each of the 16 equal
     * bands of the 8-bit range to one 4-bit level:
     *
     *   0-15   → 0    (0000)
     *   16-31  → 1    (0001)
     *   ...
     *   240-255 → 15  (1111)
     *
     * The & 0xF masks the result to exactly 4 bits, which is defensive but
     * harmless since >> 4 on a value 0-255 already fits in 4 bits.
     *
     * Example:
     *   convert8bitColorTo4bit(255) → 255 >> 4 = 15   (0b1111)
     *   convert8bitColorTo4bit(128) → 128 >> 4 = 8    (0b1000)
     *   convert8bitColorTo4bit(0)   → 0   >> 4 = 0    (0b0000)
     */
    static #convert8bitColorTo4bit(value) {
        return (value >> 4) & 0xF;
    }

    /**
     * Pack 8-bit RGB channels into a 16-bit Game Gear palette word.
     *
     * The GG palette word layout is:
     *
     *   Bit: 15 14 13 12 | 11 10  9  8 |  7  6  5  4 |  3  2  1  0
     *        (unused = 0)   B3 B2 B1 B0   G3 G2 G1 G0   R3 R2 R1 R0
     *
     * Each channel is first reduced to 4 bits via convert8bitColorTo4bit(), then placed into
     * its field by shifting:
     *
     *   Red   → bits  0-3  (no shift needed)
     *   Green → bits  4-7  (shift left 4)
     *   Blue  → bits 8-11  (shift left 8)
     *
     * Example: RGB(255, 128, 0) — full red, half green, no blue
     *   convert8bitColorTo4bit(255) = 15  (0b1111)
     *   convert8bitColorTo4bit(128) = 8   (0b1000)
     *   convert8bitColorTo4bit(0)   = 0   (0b0000)
     *
     *   result = (0 << 8) | (8 << 4) | 15
     *          = 0x0000   | 0x0080   | 0x000F
     *          = 0x008F
     *
     * This word is stored little-endian in the GG's CRAM, so bytes on disk
     * would be 0x8F, 0x00.
     */
    static #packGGColor(red, green, blue) {
        return (PNG2TileConverter.#convert8bitColorTo4bit(blue) << 8)
            | (PNG2TileConverter.#convert8bitColorTo4bit(green) << 4)
            | PNG2TileConverter.#convert8bitColorTo4bit(red);
    }
}
